name: Main Workflow
on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"
  push:
    branches:
      - "main"
jobs:
  don:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: curl
        uses: wei/curl@master
        with:
          args: https://localhost
      
